replicaCount: 1

app:
  env: local
  debug: "true"
  logChannel: stack
  logLevel: debug
  url: "http://career2.local"

queue:
  replicaCount: 1

ingress:
  enabled: true
  host: career2.local

resources:
  web:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  worker:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
  scheduler:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
